development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://rediscloud:Eg82IYDOmfdteqie9ZWcshl4g4N1CFkG@redis-12772.c2.eu-west-1-3.ec2.cloud.redislabs.com:12772" } %>
  channel_prefix: travelizer_production
